### ISSUE TITLE
Latest dart-coveralls package showing no data.

### ISSUE THREAD

**Issue by pq** [duse-io/dart-coveralls#33]
For example: https://coveralls.io/builds/2621781

Rolling back to 0.11.0 (a la `pub global activate dart_coveralls 0.1.11`) looks better: https://coveralls.io/builds/2622267

cc @kevmoo

**Comment by kevmoo** [comment]
@pq It looks like there is a timing issue.

I'm getting reports about half of the time – it's failing locally.

I'm digging in. Stay tuned.

**Comment by pq** [comment]
Thanks!

I'm rolling back a few configs to get things working.  Specifically, these should get reverted when this gets fixed:
  * https://github.com/dart-lang/which/pull/10
  * https://github.com/dart-lang/when/pull/8

**Comment by kevmoo** [comment]
This is addressed in https://github.com/duse-io/dart-coveralls/pull/32

Just waiting for it to land

**Comment by pq** [comment]
Looks fixed.  Thanks!
