### ISSUE TITLE
--upload-report functionality (upload a report, don't run tests)

### ISSUE THREAD

**Issue by sethladd** [duse-io/dart-coveralls#39]
We need to run tests in a special way, but I can generate the coverage report.

I don't need the dart_coveralls system to run the tests, just upload the report.

Thoughts on something like an `--upload-report` flag that just uploads a .json report, but doesn't actually run the tests?

**Comment by sethladd** [comment]
An example is at https://github.com/duse-io/dart-coveralls/pull/40

**Comment by sethladd** [comment]
PR for your review https://github.com/duse-io/dart-coveralls/pull/42

**Comment by Adracus** [comment]
Closing this since #42 is merged.
