### ISSUE TITLE
Ability to upload calculated coverage

### ISSUE THREAD

**Issue by ltackmann** [duse-io/dart-coveralls#49]
The current upload command only allows uploading coverage generated using 

```bash
dart --observe=NNNN test_script.dart
pub global run coverage:collect_coverage --port=NNNN -o cov-dir/cov.json --resume-isolates
```

which is then uploaded using. 

```bash
pub global run dart_coveralls upload --token my-token cov-dir
```

this is somewhat cumbersome workflow, I would much rather prefer being able to upload the reports generated by ***dart_coveralls calc*** command, i.e. something like 

```bash
pub global run dart_coveralls upload-cov --token my-token  --files cov1.json cov2.json
```

this would also be useful when merging reports

**Comment by Adracus** [comment]
As well as for the other feature, just provide a tested pull request and it'll be merged.
