### ISSUE TITLE
Ability to merge reports from multiple projects

### ISSUE THREAD

**Issue by ltackmann** [duse-io/dart-coveralls#50]
In a larger project one may have a backend, fronted and mobile (flutter) app, each within the same repository but inside different packages. As each of these have their own test script it would be nice to have the ability to run multiple scripts and combine their reports 

```bash
frontend/pubspec.yaml
frontend/packages
frontend/test/frontend_test.dart
backend/pubspec.yaml
backend/packages
backend/test/backend_test.dart
mobile/pubspec.yaml
mobile/packages
mobile/test/mobile_test.dart
```

With the current structure of dart-coveralls, its somewhat complicated to merge reports generated inside each project by hand (see #49)

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/35311534/merge-coverage-report-from-multiple-tests

**Comment by Adracus** [comment]
Sure, provide a pull request with that feature and tests and I'll merge it.
