### ISSUE TITLE
Consider adding a script to generate test_all.dart files 

### ISSUE THREAD

**Issue by jakemac53** [duse-io/dart-coveralls#51]
See https://github.com/dart-lang/build/blob/master/tool/create_test_all.dart as an example.

Since its required that you only run a single dart file, many packages today maintain a file which imports all their tests and runs them. This can easily get out of sync, and is usually pure boilerplate. A simple script like the one I linked to above can generate it automatically for most use cases.

**Comment by zoechi** [comment]
Isn't this a `test` package issue? 
When `test` and `pub` are changed so `pub run` runs in an isolate instead of a new process (which I is planned AFAIK) then `pub run test` should allow to collect coverage information and `pub run test` would take care of running all test files.

**Comment by jakemac53** [comment]
I do see https://github.com/dart-lang/test/issues/36 in the test package. The solution I linked above works today though (for vm tests at least). I am fine with just copying that into any of my packages that need it in the meantime though.

**Comment by Adracus** [comment]
I think that approach would lead to the issue that a file is being generated and reports are generated for that file and sent to coveralls. On coveralls then there would be a file that is not tracked in git which would lead to confusion in my opinion. A more clean approach is to really have one file that is also tracked in git that fulfills this purpose.
